runtime: nodejs

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: public/static
    expiration: 30d

# manual_scaling - Lock instances to 1 . using App Engine Flexible will create VM instances to serve from. If you want to lower your usage, you might restrict your App to just one 1 instance (probably not what you want in production, but perfect for in prototyping and development cases ).
# https://stackoverflow.com/questions/37381694/google-app-engine-how-to-correctly-deploy-an-app
