import mongoose from 'mongoose';
import passportLocalMongoose from 'passport-local-mongoose';

const userSchema = new mongoose.Schema({
  // add your needed Values
  // Username, Password, Hash and Salt will get generated by passport
});

userSchema.plugin(passportLocalMongoose);

export default mongoose.model('User', userSchema);
